FROM ubuntu:15.04
# 更新阿里源
COPY sources.list /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update

# 解决 debconf: unable to initialzie frontend: Dialog
ENV DEBIAN_FRONTEND noninteractive

# 添加64位系统对32位支持
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y lib32z1 lib32ncurses5 lib32bz2-1.0

# 安装源码所需编译工具
RUN sudo apt-get install libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-dev g++-multilib 
RUN sudo apt-get install -y git flex bison gperf build-essential libncurses5-dev:i386 
RUN sudo apt-get install tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386 
RUN sudo apt-get install dpkg-dev libsdl1.2-dev libesd0-dev
RUN sudo apt-get install git-core gnupg flex bison gperf build-essential  
RUN sudo apt-get install zip curl zlib1g-dev gcc-multilib g++-multilib 
RUN sudo apt-get install libc6-dev-i386 
RUN sudo apt-get install lib32ncurses5-dev x11proto-core-dev libx11-dev 
RUN sudo apt-get install libgl1-mesa-dev libxml2-utils xsltproc unzip m4
RUN sudo apt-get install lib32z-dev ccache

# 配置java环境
# 注：Android5.x - Android 6.0编译需要用jdk7，Android7.0及其以上需要用jdk8
RUN apt-get install -y openjdk-8-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV CLASS_PATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH=$JAVA_HOME/bin:$PATH
