FROM ubuntu:15.04

WORKDIR /aosp
ENV USER root

# 更新阿里源
COPY sources.list /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update

# 解决 debconf: unable to initialzie frontend: Dialog
ENV DEBIAN_FRONTEND noninteractive

# 添加64位系统对32位支持
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y lib32z1 lib32ncurses5 lib32bz2-1.0

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip python && \
    mkdir -p /android_build/bin && \
    curl https://storage.googleapis.com/git-repo-downloads/repo > /android_build/bin/repo && \
    chmod a+x /android_build/bin/repo && \
    rm -rf /var/cahce/apt && \
    rm -rf /var/lib/apt/lists

RUN apt-get update && \
    apt-get install -y bc imagemagick ccache schedtool && \
    rm -rf /var/cache/apt && \
    rm -rf /var/lib/apt/lists